In [3]:
%pip install numpy
def homework(message):
    print("\n>>>>>", message, "\n")

In [4]:
import numpy as np
temperature = [20.1, 20.1, 20.2, 20.4]
print(temperature)

t1 = temperature * 5

print(f"При множенні на 5 маємо: {t1}")
homework("Чому маємо такий результат? ")
print("Це пов'язано з тим що тут використано просте множення списку приводить до повторення його елементів, а не множення кожного елементу на 5.")

t1 = [ x*5 for x in temperature] 
print(f"Тепер отримаємо: {t1}") 
homework("Чому тепер множення успішне? ")
print("Це пов'язано з тим що тут використано списковий вираз для множення кожного елементу списку на 5, і отримали очікуваний результат.")

t2 = np.array(temperature)
print("Масив з використанням методів NumPy", t2)

t3 = t2 * 5
print("При множенні на 5 отримуємо:", t3)

[20.1, 20.1, 20.2, 20.4]
При множенні на 5 маємо: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]

>>>>> Чому маємо такий результат?  

Це пов'язано з тим що тут використано просте множення списку приводить до повторення його елементів, а не множення кожного елементу на 5.
Тепер отримаємо: [100.5, 100.5, 101.0, 102.0]

>>>>> Чому тепер множення успішне?  

Це пов'язано з тим що тут використано списковий вираз для множення кожного елементу списку на 5, і отримали очікуваний результат.
Масив з використанням методів NumPy [20.1 20.1 20.2 20.4]
При множенні на 5 отримуємо: [100.5 100.5 101.  102. ]


## Вектори, створення та робота з ними

In [5]:
print("Все можна сторити вручну за допомогою методу np.array передавши йому набір значень у вигляді List:")
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row, "\nВектор має розмір", vector_row.shape)
print(vector_column, "\nВектор має розмір", vector_column.shape)

Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:
[[ 1 -5  3  2  4]] 
Вектор має розмір (1, 5)
[[1]
 [2]
 [3]
 [4]] 
Вектор має розмір (4, 1)


## Метод arange - генерує послідовність чисел з певним кроком у заданому інтервалі

In [7]:
import numpy as np

start = 5
size_of_vec = 100
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {list(x)}")
print(f"Масив згенерований методом arange: {a}")
homework("Вивів весь діапазон чисел.")

a = np.arange(start, size_of_vec)
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[0]}")
print(f"Останній діапазон в згенерованому масиві: {a[-1]}")
homework("Вивів останній діапазон в згенерованому масиві.")

x = range(start, size_of_vec)
print("Те саме але з вбудованою функцією range:", x)
print("Власне вивід значень:", list(x)[0], )
mid_value_arange = a[len(a) // 2]
print(f"Число з середини діапазону (за допомогою arange): {mid_value_arange}")
homework("Вивів число з середини діапазону.")

# дробові числа
x = np.arange(10.4)
print("Будем мати:", x)
# крок
x = np.arange(0.5, 4, 0.5)
print("З кроком 0.5:", x)
# Заокруглення
x = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", x,)
# масив
x = np.arange(0, 1, 0.0001)
print("Масив з кроком 0.0001:", x)

homework("Згенерував значення де крок 0.0001")
y = x * 2.5
result = (y * y) / 0.4 
print("Після перемноження:", y)
print("Після перемноження та підняття до ступеня та поділу на 0.4:", result)
homework("Підніс отримане число до ступеня та поділив на 0.4")


Масив згенерований простим range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
Масив згенерований методом arange: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

>>>>> Вивів весь діапазон чисел. 

Можемо задавати початок генерації вектора, перший елемент: 5
Останній діапазон в згенерованому масиві: 99

>>>>> Вивів останній діапазон в згенерованому масиві. 

Те саме але з вбудованою функцією r

## Метод linspace - генерує задану кількістю чисел у певному діапазоні, 50 чисел за замовчуванням

In [8]:
import numpy as np

start = 1  # Початкове значення
size_of_vec = 100  # Кількість елементів у векторі

a = np.linspace(start, size_of_vec)
print(f"Згенерували {len(a)} чисел в діапазоні {a[0]} до {a[-1]}")
#print(f"Власне числа: {a}")

# Виведення перших та останніх 10 чисел
print("Перші 10 чисел:")
print(a[:10])

print("Останні 10 чисел:")
print(a[-10:])

# Визначення кроку
step = (a[-1] - a[0]) / (len(a) - 1)
print(f"Крок: {step}")

print("Кожне друге число:")
for i in range(0, len(a), 2):
    print(a[i])
homework("Вивів кожне друге число згенерованого діапазону :)")

print("Можна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(a)

print("Розрахунок кроку без останнього значення:")
step_without_endpoint = (a[-1] - a[0]) / len(a)
print(f"Крок без останнього значення: {step_without_endpoint}")

homework("Збільшив кількість чисел до 100. Вивів перших та останніх 10.")

print("""Як бачимо перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.
""")

print(np.linspace(start, size_of_vec, 5, endpoint=False))
homework("Порахував крок.")

_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print(f"Для порівняння, ми можемо визначити крок автоматично, у нашому випадку це {sp_1} та {sp_2}")
homework("Чому маємо такий крок?")
print(f"У першому прикладі, де ми встановили endpoint=True, крок визначається як різниця між останнім і першим значеннями, поділена на кількість елементів у векторі, включаючи останнє значення. ")
print(f"У другому прикладі, де ми встановили endpoint=False, крок визначається як різниця між останнім і першим значеннями, поділена на кількість елементів у векторі, виключаючи останнє значення.")

Згенерували 50 чисел в діапазоні 1.0 до 100.0
Перші 10 чисел:
[ 1.          3.02040816  5.04081633  7.06122449  9.08163265 11.10204082
 13.12244898 15.14285714 17.16326531 19.18367347]
Останні 10 чисел:
[ 81.81632653  83.83673469  85.85714286  87.87755102  89.89795918
  91.91836735  93.93877551  95.95918367  97.97959184 100.        ]
Крок: 2.020408163265306
Кожне друге число:
1.0
5.040816326530612
9.081632653061224
13.122448979591836
17.163265306122447
21.204081632653057
25.24489795918367
29.285714285714285
33.326530612244895
37.367346938775505
41.408163265306115
45.44897959183673
49.48979591836734
53.53061224489795
57.57142857142857
61.61224489795918
65.65306122448979
69.6938775510204
73.73469387755101
77.77551020408163
81.81632653061223
85.85714285714285
89.89795918367346
93.93877551020407
97.97959183673468

>>>>> Вивів кожне друге число згенерованого діапазону :) 

Можна зменшити кількість чисел до 5:
[  1.    25.75  50.5   75.25 100.  ]
Розрахунок кроку без останнього значення:
Кро

## Типи масивів/векторів

In [9]:
import numpy as np

examples = {
    'Скаляр': np.array(5), 
    'Вектор Рядок': np.array([1, 2, 3, 4, 5]), 
    'Вектор Стовпець': np.array([[1], [2], [3], [4]]), 
    'Матриця': np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]]),
    'Багатовимірна Матриця': np.array([ [[1, 2], [3, 4]],
                                        [[5, 6], [7, 8]]])
    }
for key in examples:
    print(f"Розглядаємо приклад з {key}. \nЗначення x буде: \n", examples[key])
    print(f"Тип {key} x: ", type(examples[key]))
    print(f"Розмірність/вимір {key} x:", np.ndim(examples[key]))
    print(f"Форма {key} x: ", examples[key].shape)
    print(f"Кількість елементів х: {np.size(examples[key])}")
    print("-=-"*10)

homework("""Як Ви думаєте чому маємо такий результат для функції np.ndim (Розмірність/вимір/dimension).
Чому значення для векторів та матриць однакове та не співпдає з значенням shape?
Задала власні вектори з різними числами.""")
print(f"Функція np.ndim повертає кількість вимірів (розмірність) масиву. Розмірність масиву визначається кількістю його вкладених списків. \nТаким чином, розмірність масиву визначається кількістю вкладених рівнів списків у структурі даних, а не числом осей у просторі. У випадку одномірних масивів, розмірність все одно визначається як 1.")
print(f"Значення та форма пов'язані з вмістом об'єкта, а розмірність вказує на кількість вимірів об'єкта. \nФорма і розмірність відображають різні аспекти об'єкта, і вони можуть бути різними навіть для об'єктів з однаковою кількістю вимірів.")

Розглядаємо приклад з Скаляр. 
Значення x буде: 
 5
Тип Скаляр x:  <class 'numpy.ndarray'>
Розмірність/вимір Скаляр x: 0
Форма Скаляр x:  ()
Кількість елементів х: 1
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Рядок. 
Значення x буде: 
 [1 2 3 4 5]
Тип Вектор Рядок x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Рядок x: 1
Форма Вектор Рядок x:  (5,)
Кількість елементів х: 5
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Стовпець. 
Значення x буде: 
 [[1]
 [2]
 [3]
 [4]]
Тип Вектор Стовпець x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Стовпець x: 2
Форма Вектор Стовпець x:  (4, 1)
Кількість елементів х: 4
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Матриця. 
Значення x буде: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Тип Матриця x:  <class 'numpy.ndarray'>
Розмірність/вимір Матриця x: 2
Форма Матриця x:  (3, 3)
Кількість елементів х: 9
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Багатовимірна Матриця. 
Значення x буде: 
 [[[1 2]
  [3 4]]



Метод np.shape дозволяє зрозуміти виріми масиву і подає їх як (кількість рядків, кількість стовпців, кількість елементів).

In [10]:
examples = {
    '5 рядків': np.array([[1], [2], [3], [4], [5]]), 
    '5 стовпців': np.array([[1, 2, 3, 4, 5]]),
    '5 елементів': np.array([[[1, 2, 3, 4, 5]]])
    }
for a in examples:
    print(f"Для {a} маємо shape: \n{examples[a].shape} \nта вигляд: \n{examples[a]}")

homework(f"Створив власні масиви з різною кількістю елементів та використав метод shape для визначення їх вимірів.")

Для 5 рядків маємо shape: 
(5, 1) 
та вигляд: 
[[1]
 [2]
 [3]
 [4]
 [5]]
Для 5 стовпців маємо shape: 
(1, 5) 
та вигляд: 
[[1 2 3 4 5]]
Для 5 елементів маємо shape: 
(1, 1, 5) 
та вигляд: 
[[[1 2 3 4 5]]]

>>>>> Створив власні масиви з різною кількістю елементів та використав метод shape для визначення їх вимірів. 



## Створенні власні масиви:

In [11]:
import numpy as np

# Масив з одним рядком та п'ятьма стовпцями
array1 = np.array([[1, 2, 3, 4, 5]])

# Масив з п'ятьма рядками та одним стовпцем
array2 = np.array([[1], [2], [3], [4], [5]])

# Тривимірний масив з одним елементом
array3 = np.array([[[1, 2, 3, 4, 5]]])

# Вивід shape та вмісту кожного масиву
print("Масив array1 має shape:", array1.shape, "та вигляд:", array1)
print("Масив array2 має shape:", array2.shape, "та вигляд:", array2)
print("Масив array3 має shape:", array3.shape, "та вигляд:", array3)


Масив array1 має shape: (1, 5) та вигляд: [[1 2 3 4 5]]
Масив array2 має shape: (5, 1) та вигляд: [[1]
 [2]
 [3]
 [4]
 [5]]
Масив array3 має shape: (1, 1, 5) та вигляд: [[[1 2 3 4 5]]]


## Indexing and Slicing

In [12]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
print(f"""Масив: {F}
Виміри: {F.shape}
Памятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву:\n {F[0]}
Другий:\n {F[1]}
Останній, {len(F)}: \n {F[7]}""")

print(f"""Можемо скористатись відємними індексами якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент:\n {F[-1]}
Передостанній:\n {F[-2]}""")

homework("Попрактикувався з доступністю до елементів, вивів декілька елементів різними способами.")

# Вивести перші три елементи
print("Перші три елементи:", F[:3])

# Вивести елементи з індексами 2 по 5 (включно)
print("Елементи з індексами 2 по 5:", F[2:6])

# Вивести всі елементи масиву за допомогою циклу
print("Всі елементи масиву:")
for element in F:
    print(element)

# Вивести перші три елементи за допомогою numpy.take
print("Перші три елементи:", np.take(F, [0, 1, 2]))


Масив: [ 1  1  2  3  5  8 13 21]
Виміри: (8,)
Памятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву:
 1
Другий:
 1
Останній, 8: 
 21
Можемо скористатись відємними індексами якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент:
 21
Передостанній:
 13

>>>>> Попрактикувався доступатись до елементів, вивів декілька елементів різними способами. 

Перші три елементи: [1 1 2]
Елементи з індексами 2 по 5: [2 3 5 8]
Всі елементи масиву:
1
1
2
3
5
8
13
21
Перші три елементи: [1 1 2]


In [13]:
import numpy as np

A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8],
               [7.0, -3.9, 5.1]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення то візьметься цілий рядок:
    Перший рядок: {A[0]}
    Останній рядок: {A[-1]}
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: {A[:,0]}
    Останній стовпець: {A[:,-1]}
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: {A[0][0]} або {A[0, 0]}
    Останній елемент: {A[3][2]} або {A[-1][-1]} або {A[3, -1]}
""")

homework("Попрактикувався в доступі до багатовимірного масиву, вивів елементи які належать діагоналі.")

rows, cols = A.shape

print("Елементи на діагоналі:")
for i in range(min(rows, cols)):
    print(A[i, i])

Масив:
[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]
 [ 7.  -3.9  5.1]]
Виміри: (4, 3)
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення то візьметься цілий рядок:
    Перший рядок: [3.4 8.7 9.9]
    Останній рядок: [ 7.  -3.9  5.1]
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: [3.4 1.1 4.1 7. ]
    Останній стовпець: [ 9.9 -0.7  4.8  5.1]
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: 3.4 або 3.4
    Останній елемент: 5.1 або 5.1 або 5.1


>>>>> Попрактикувався в доступі до багатовимірного масиву, вивів елементи які належать діагоналі. 

Елементи на діагоналі:
3.4
-7.8
4.8


## Принцип доступу до елементів  S[start:stop:step]. Елемент stop не включається у вивід.

In [14]:
import numpy as np

S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(f"""Масив:
{S}
Виміри: {S.shape}
Беремо декілька елементів: {S[2:5]}
Всі елементи до заданого: {S[:4]}
Всі елементи від заданого до кінця: {S[6:]}
Всі елементи: {S[:]}
Останні 4 елементи: {S[-4:]}
""")
homework("Попрактикувався у витягуванні елементів, взяв 4 значення з кінця масиву.")



Масив:
[0 1 2 3 4 5 6 7 8 9]
Виміри: (10,)
Беремо декілька елементів: [2 3 4]
Всі елементи до заданого: [0 1 2 3]
Всі елементи від заданого до кінця: [6 7 8 9]
Всі елементи: [0 1 2 3 4 5 6 7 8 9]
Останні 4 елементи: [6 7 8 9]


>>>>> Попрактикувався у витягуванні елементів, взяв 4 значення з кінця масиву. 



## Принцип Slicing може використовуватись для багатовимірних масивів.

In [15]:
import numpy as np

A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо декілька рядків: 
{A[0:2]}
Два перші стовпці: 
{A[:, 0:2]}
Два останні рядки:
{A[3:, :]}
Беремо підматрицю (нижні елементи): 
{A[-3:, -3:]}
""")
homework("Попрактикувався у витягуванні елементів, взяв матрицю 2х2 з нижнього та верхнього кутка матриці А.")

upper_left = A[:2, :2]  # верхній лівий кут
lower_right = A[-2:, -2:]  # нижній правий кут

print(f"Верхній лівий кут 2x2:\n{upper_left}")
print(f"Нижній правий кут 2x2:\n{lower_right}")

Масив:
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]
Виміри: (5, 5)
Беремо декілька рядків: 
[[11 12 13 14 15]
 [21 22 23 24 25]]
Два перші стовпці: 
[[11 12]
 [21 22]
 [31 32]
 [41 42]
 [51 52]]
Два останні рядки:
[[41 42 43 44 45]
 [51 52 53 54 55]]
Беремо підматрицю (нижні елементи): 
[[33 34 35]
 [43 44 45]
 [53 54 55]]


>>>>> Попрактикувався у витягуванні елементів, взяв матрицю 2х2 з нижнього та верхнього кутка матриці А. 

Верхній лівий кут 2x2:
[[11 12]
 [21 22]]
Нижній правий кут 2x2:
[[44 45]
 [54 55]]


## Slicing дозволяє брати не тільки послідовні значення але із заданим кроком.

In [16]:
A = np.arange(28).reshape(4, 7)

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо кожен дугий елемент першого рядка: 
{A[0, ::2]}
Беремо кожен третій елемент першого рядка: 
{A[0, ::3]}
Кожен другий елемент в кожномуу другому рядку: 
{A[::2, ::2]}
Останні три елементи в кожному другому рядку:
{A[::2, 4:]}
Можна повнісню змінити порядок елементів (дзерально обернемо):
{A[::-1, ::-1]}
Додаткове витягування: Витягуємо тільки парні числа в масиві:
{A[A % 2 == 0]} 
""")
#Додаткове витягування: Вивести середні значення кожного стовпця:
column_means = np.mean(A, axis=0)
print(f"Середні значення кожного стовпця: {column_means}")

homework("Попрактикувався у витягуванні елементів, будь-яка робоча комбінація.")

Масив:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
Виміри: (4, 7)
Беремо кожен дугий елемент першого рядка: 
[0 2 4 6]
Беремо кожен третій елемент першого рядка: 
[0 3 6]
Кожен другий елемент в кожномуу другому рядку: 
[[ 0  2  4  6]
 [14 16 18 20]]
Останні три елементи в кожному другому рядку:
[[ 4  5  6]
 [18 19 20]]
Можна повнісню змінити порядок елементів (дзерально обернемо):
[[27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14]
 [13 12 11 10  9  8  7]
 [ 6  5  4  3  2  1  0]]
Додаткове витягування: Витягуємо тільки парні числа в масиві:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26] 

Середні значення кожного стовпця: [10.5 11.5 12.5 13.5 14.5 15.5 16.5]

>>>>> Попрактикувався у витягуванні елементів, будь-яка робоча комбінація. 



## Вибірка елементів по умові

In [17]:
import numpy as np

A = np.arange(50)
all_even = (A%2==0) # парні
complex = (A<30) & (A/5<2) 

all_odd = (A % 2 != 0)  # непарні

print(f"""Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або {all_even[0]} для {A[0]} або {all_even[1]} для {A[1]}.
Після підставляння умови пошуку парних чисел в масив отримаємо:
{A[all_even]}
Або застосувавати більш комплексну умову з двох порінянь:
{A[complex]}""")
print(f"Всі непарні числа з масиву A:\n{A[all_odd]}")

homework("Вивів всі непарні числа з даного масиву.")

Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або True для 0 або False для 1.
Після підставляння умови пошуку парних чисел в масив отримаємо:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
Або застосувавати більш комплексну умову з двох порінянь:
[0 1 2 3 4 5 6 7 8 9]
Всі непарні числа з масиву A:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]

>>>>> Вивів всі непарні числа з даного масиву. 



## Функції для створення матриць: ones, zeros, identity, eye, empty

In [18]:
o = np.ones(5)
z = np.zeros(5)
i = np.identity(5)
e = np.eye(5)
t = np.empty(5)

print(f"""
Всі елементи 1:
{o}
Всі елементи 0:
{z}
Матриця в якої діагональ всі 1:
{i}
Також, діагональ всі 1 (зменшимо вивід):
{e[:2, :2]}
Пуста матриця буде містити набір випадкових чисел які записані у память де був ініціалізований масив:
{t}
""")


Всі елементи 1:
[1. 1. 1. 1. 1.]
Всі елементи 0:
[0. 0. 0. 0. 0.]
Матриця в якої діагональ всі 1:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Також, діагональ всі 1 (зменшимо вивід):
[[1. 0.]
 [0. 1.]]
Пуста матриця буде містити набір випадкових чисел які записані у память де був ініціалізований масив:
[ 1.  20.8 40.6 60.4 80.2]



## Визначити за якою формулою генеруються значення для методу arange?
Метод arange генерує послідовність рівномірно розподілених чисел від початку до кінця заданого інтервалу. Формула для генерації таких чисел така:
'x = start + step * (i - 1)'

## Визначити формулу для методу linspace?
Метод linspace генерує послідовність рівномірно розподілених чисел від початку до кінця заданого інтервалу, включаючи кінцевий елемент. Формула для генерації таких чисел така:
'x = start + (end - start) * (i / (num - 1))'

## Порівняйте формули, для яких випадків вони можуть застосовуватись?
Основна відмінність між формулами для методів arange та linspace полягає в тому, що метод arange включає початкове значення інтервалу в послідовність, а метод linspace - ні.
Крім того, метод linspace дозволяє вказати кількість елементів послідовності, а метод arange - ні.
Застосування
Методи arange та linspace можна використовувати в різних випадках. Наприклад, вони можуть бути використані для створення послідовності чисел для графіка, для створення послідовності значень для ітераційного циклу або для створення послідовності значень для навчання моделі машинного навчання.

## Створіть декілька простих Векторів та Матриць та виведіть їх розмірність. Виконайте арифметичні операції над створеними Векторам/Матрицями;

In [3]:
import numpy as np

# Створення векторів
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])

# Виведення розмірності векторів
print("Розмір вектора A:", vector_a.shape)
print("Розмір вектора B:", vector_b.shape)

# Створення матриць
matrix_A = np.array([[1, 2, 3], [4, 5, 6]])
matrix_B = np.array([[7, 8, 9], [10, 11, 12]])

# Виведення розмірності матриць
print("Розмір матриці A:", matrix_A.shape)
print("Розмір матриці B:", matrix_B.shape)

# Арифметичні операції
sum_vector = vector_a + vector_b
difference_vector = vector_a - vector_b
elementwise_product_vector = vector_a * vector_b
dot_product_vector = np.dot(vector_a, vector_b)

sum_matrix = matrix_A + matrix_B
difference_matrix = matrix_A - matrix_B
elementwise_product_matrix = matrix_A * matrix_B
matrix_product = np.dot(matrix_A, matrix_B.T)  # Транспонуємо матрицю B перед множенням

# Виведення результатів
print("\nОперації з векторами:")
print("Сума:", sum_vector)
print("Різниця:", difference_vector)
print("Поелементний добуток:", elementwise_product_vector)
print("Добуток:", dot_product_vector)

print("\nОперації з матрицями:")
print("Сума:\n", sum_matrix)
print("Різниця:\n", difference_matrix)
print("Поелементний добуток:\n", elementwise_product_matrix)
print("Добуток матриць:\n", matrix_product)


Розмір вектора A: (3,)
Розмір вектора B: (3,)
Розмір матриці A: (2, 3)
Розмір матриці B: (2, 3)

Операції з векторами:
Сума: [5 7 9]
Різниця: [-3 -3 -3]
Поелементний добуток: [ 4 10 18]
Добуток: 32

Операції з матрицями:
Сума:
 [[ 8 10 12]
 [14 16 18]]
Різниця:
 [[-6 -6 -6]
 [-6 -6 -6]]
Поелементний добуток:
 [[ 7 16 27]
 [40 55 72]]
Добуток матриць:
 [[ 50  68]
 [122 167]]
